language: ruby

matrix:
  include:
    - rvm: 2.1.10
      os: linux
    - rvm: 2.2.5
      os: linux
    - rvm: 2.3.1
      os: linux
    - rvm: ruby-head
      os: linux
    - rvm: jruby-9.0.5.0
      os: linux
  allow_failures:
    - rvm: ruby-head

cache: bundler

addons:
  apt:
    packages:
    - graphviz
