language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.6.0
  - jruby-head
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  apt:
    packages:
      - graphviz
