language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - jruby-head
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  apt:
    packages:
      - graphviz
